name: truenorthdemoproject
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  loading_animation_widget: ^1.3.0
  flutter_material_symbols: ^0.0.4
  flutter_symbols: ^1.0.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.2.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  location: ^7.0.1
  http: ^1.3.0
  mime: ^1.0.4
  intl: ^0.18.1

  cupertino_icons: ^1.0.8

  http_parser: ^4.1.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_charts: ^0.5.2
  syncfusion_flutter_charts: ^30.1.41
  platform: ^3.1.6
  adaptive_scrollbar: ^2.1.2
  flutter_background_service: ^5.1.0
  
  package_info_plus: ^4.0.0
  dio: ^5.0.0
  open_filex: ^4.0.0
  path_provider: ^2.0.0
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/font/companyLogo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/
